#pragma once

#include <SDL2/SDL.h>

#define NEWLINE '\n'

namespace util{
    namespace constants{
        const int CELL_LENGTH=64;
        const int CELL_COUNT_HORIZONTAL=10;
        const int CELL_COUNT_VERTICAL=10;
        const int WINDOW_WIDTH=CELL_LENGTH*CELL_COUNT_HORIZONTAL;
        const int WINDOW_HEIGHT=CELL_LENGTH*CELL_COUNT_VERTICAL;
        const int NUMBER_OF_COLOURS=6;

        const int GEM_TEXTURE_LENGTH=192;
        const SDL_Rect GEM_TEXTURE_REGIONS[NUMBER_OF_COLOURS]{
            SDL_Rect{0,0,GEM_TEXTURE_LENGTH,GEM_TEXTURE_LENGTH},
            SDL_Rect{1*GEM_TEXTURE_LENGTH,0,GEM_TEXTURE_LENGTH,GEM_TEXTURE_LENGTH},
            SDL_Rect{2*GEM_TEXTURE_LENGTH,0,GEM_TEXTURE_LENGTH,GEM_TEXTURE_LENGTH},
            SDL_Rect{3*GEM_TEXTURE_LENGTH,0,GEM_TEXTURE_LENGTH,GEM_TEXTURE_LENGTH},
            SDL_Rect{4*GEM_TEXTURE_LENGTH,0,GEM_TEXTURE_LENGTH,GEM_TEXTURE_LENGTH},
            SDL_Rect{5*GEM_TEXTURE_LENGTH,0,GEM_TEXTURE_LENGTH,GEM_TEXTURE_LENGTH},
        };
    }
}